#!/bin/sh

#exec xwinwrap -ov -g 1920x1080+0+0 -- mpv -wid WID /home/raiku/Misc/McShaders.mp4 --no-osc --no-osd-bar --loop-file --no-audio --player-operation-mode=cplayer --panscan=1.0 --no-input-default-bindings --gpu-api=opengl --vo=gpu --hwdec=vaapi

# if true; then
  # sleep 2
  # .home/arch/.dwm/start_jack.py
  # sleep 4
  # systemctl --user start pulseuadio
  # jack_disconnect system:capture_1 "PulseAudio JACK Source:front-left"
  # jack_disconnect system:capture_2 "PulseAudio JACK Source:front-right"
  # carla /home/arch/Misc/Carla/1.carxp --nogui &
  # alsa_out -j "Speakers" -d hdmi:NVidia,0 &
  # systemctl --user start fluidsynth
# fi &

for i in $(seq 20); do 
  wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.18
  sleep 1
done &

if ! pgrep funckeysd &> /dev/null; then
  /usr/local/bin/funckeysd
fi

