#!/bin/sh

#exec xwinwrap -ov -g 1920x1080+0+0 -- mpv -wid WID /home/raiku/Misc/McShaders.mp4 --no-osc --no-osd-bar --loop-file --no-audio --player-operation-mode=cplayer --panscan=1.0 --no-input-default-bindings --gpu-api=opengl --vo=gpu --hwdec=vaapi

if ! pgrep funckeysd &> /dev/null; then
  /usr/local/bin/funckeysd
fi &

xset r rate 200 50
setxkbmap -option caps:swapescape
if true; then
  sleep 5
  xset r rate 200 50
  setxkbmap -option caps:swapescape
fi &

POWERED="0"
while true; do
  POWER="$(cat /sys/class/power_supply/BAT1/capacity)"
  POWER_STATUS="$(cat /sys/class/power_supply/BAT1/status)"
  if [ $POWER -le "5" -a $POWERED = "0"  -a $POWER_STATUS != "+"]; then
    herbe "Low on power!"
    POWERED="1"
  elif [ $POWER -gt "10" ]; then
    POWERED="0"
  fi
  sleep 5s
done

