#!/bin/sh

xset -b # disable bell

xrandr --output DP-0 --mode 1920x1080 --rate 240 &

setxkbmap -option caps:swapescape
xset r rate 200 50

if ! pgrep r2kd &> /dev/null; then
  r2kd
fi
if ! pgrep ankeed &> /dev/null; then
  ankeed &
fi
if ! pgrep sarmale &> /dev/null; then
  sarmale &
fi
if ! pgrep vmware-usbarbitrator &> /dev/null; then
  sudo vmware-usbarbitrator
fi
# if ! pgrep spotifyd &> /dev/null; then
  # spotifyd --no-daemon &> /dev/null &
# fi

while true; do
  LOCALTIME=$(date +"%d/%m/%Y %H:%M")
  
  SPOTIFY_STATUS="$(/usr/local/bin/get_spotify_song)"

  VPN="$(get_vpn)"
  
  xsetroot -name "$VPN$SPOTIFY_STATUS$LOCALTIME"
  sleep 5s 
done &

hsetroot -fill /home/arch/Misc/Bgs/Mandelbrot.png
doas sysctl abi.vsyscall32=0
nvidia-modprobe

if true; then
  xset r rate 200 50
  setxkbmap -option caps:swapescape
  sleep 1
  xset r rate 200 50
  setxkbmap -option caps:swapescape
  sleep 1
  xset r rate 200 50
  setxkbmap -option caps:swapescape
  sleep 1
  xset r rate 200 50
  setxkbmap -option caps:swapescape
  sleep 1
  xset r rate 200 50
  setxkbmap -option caps:swapescape
  sleep 1
  xset r rate 200 50
  setxkbmap -option caps:swapescape
  sleep 1
  xset r rate 200 50
  setxkbmap -option caps:swapescape
fi &

exec dwm
