#!/bin/sh


printvol() {
  VOL=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
  VOL=${VOL#* }
  VOL=$(echo "$VOL * 100" | bc -l)
  VOL=${VOL%.*} 
  herbe "" "The volume is now $VOL%" "" &
}

case $1 in
  ++)
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.1+
    printvol
    ;;
  --)
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.1-
    printvol
    ;;
  +)
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05+
    printvol
    ;;
  -)
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05-
    printvol
    ;;
  t)
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    herbe "" "Toggled the sound" "" &
    ;;
  *)
    echo "INVALID COMMAND"
    ;;
esac
