#!/bin/sh


printvol() {
  VOL=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
  VOL=${VOL#* }
  VOL=$(echo "$VOL * 100" | bc -l)
  VOL=${VOL%.*} 
  if [ -n $XDG_SEAT ]; then
    plant "" "The volume is now $VOL%" "" &> /dev/null &
  else
    herbe "" "The volume is now $VOL%" "" &> /dev/null &
  fi
}

case $1 in
  ++)
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.1+
    printvol
    ;;
  --)
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.1-
    printvol
    ;;
  +)
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05+
    printvol
    ;;
  -)
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05-
    printvol
    ;;
  t)
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    if [ -n $XDG_SEAT ]; then
      plant "" "Toggled the sound" "" &> /dev/null &
    else
      herbe "" "Toggled the sound" "" &> /dev/null &
    fi
    ;;
  *)
    echo "INVALID COMMAND"
    ;;
esac
