#!/bin/sh


WPAPID=$(_get_wdpid wpa0)
DCPPID=$(_get_wdpid dhcp0)
doas ip a flush dev wlan0
doas kill $WPAPID &> /dev/null
doas kill $DCPPID &> /dev/null
sleep 0.2
doas rm /run/wpa_supplicant/wlan0
doas kill $WPAPID &> /dev/null
doas kill $DCPPID &> /dev/null
sleep 0.2
doas rm /run/wpa_supplicant/wlan0

doas wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant_hotspot.conf &

doas dhcpcd wlan0
