#!/bin/sh


WPAPID=$(_get_wdpid wpa0)
DCPPID=$(_get_wdpid dhcp0)
sudo ip a flush dev wlan0
kill $WPAPID &> /dev/null
kill $DCPPID &> /dev/null
sleep 0.2
rm /run/wpa_supplicant/wlan0
kill $WPAPID &> /dev/null
kill $DCPPID &> /dev/null
sleep 0.2
rm /run/wpa_supplicant/wlan0

wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant_hotspot.conf &

dhcpcd wlan0
