#!/bin/sh

if [ $# != 2 ]; then
  echo "Usage ./connect_milena \"<Network name>\" \"<Network password>\""
  exit 2
fi

sudo rm /tmp/wpa.conf
echo "ctrl_interface=/run/wpa_supplicant" > /tmp/wpa.conf
echo "update_config=1" >> /tmp/wpa.conf
echo "network={" >> /tmp/wpa.conf
echo "	ssid=\"$1\"" >> /tmp/wpa.conf
if [ "$2" == "" ]; then
  echo "key_mgmt=NONE" >> /tmp/wpa.conf
else
  echo "	psk=\"$2\"" >> /tmp/wpa.conf
fi
echo "}" >> /tmp/wpa.conf

doas connect_wpa /tmp/wpa.conf
