#!/bin/sh
[ $1 ]
if [ $? == 1 ]; then
  echo "Usage: dict [--a|--w|--r] word"
  exit 1
fi

if [ $1 == "--a" ]; then
	rg --color=auto -iw "$2" ~/Misc/Dict.csv
	exit 0
fi

if [ $1 == "--w" ]; then
	rg --color=auto -iw "^$2" ~/Misc/Dict.csv
  exit 0
fi

if [ $1 == "--r" ]; then
  sed -n $(shuf -i 1-176049 -n 1)"p" ~/Misc/Dict.csv
  exit 0
fi

rg --color=auto -ie "^$1" ~/Misc/Dict.csv

