#!/bin/python3

import sys
import re

def usage(e):
    print('')
    print('Usage:')
    print('  fix_yt_vtt {file_to_fix}')
    print('')
    exit(e)

if len(sys.argv) < 2:
    usage(1)

with open(sys.argv[1], 'r') as f:
    s = f.read()

lines = s.split('\n')

def gc(last, line):
    if '-->' in line:
        return 1
    else:
        if last == 1:
            return 2
        else:
            return last

def fix(line, old):
    s = r'<.*?>'
    cr = re.sub(s, '', line)
    if cr in old:
        return ''
    return cr

def get_data(line):
    sp = line.split(' ')
    return [sp[0], sp[2], ' '.join(sp[3:len(sp)])]

last = 3
curlines = []
lastlines = []

init_text = ''
sub = []
subentry = {'start': '', 'end': '', 'extra_text': '', 'subs': []}

def cadd(entry):
    if entry['start'] == '':
        return
    if len(entry['subs']) == 0 and len(sub) > 0:
        sub[-1]['end'] = entry['end']
        return
    sub.append(entry)

for l in lines:
    cur = gc(last, l)
    if cur == 3:
        init_text += f'{l}\n'

    if cur == 1:
        cadd(subentry)
        a = get_data(l)
        subentry = {'start': a[0], 'end': a[1], 'extra_text': a[2], 'subs': []}
        lastlines = curlines
        curlines = []

    if cur == 2:
        if len(sub) > 0:
            cl = fix(l, sub[-1]['subs'])
        else:
            cl = fix(l, [])
        if cl != '' and cl != ' ':
            subentry['subs'].append(cl)

    last = cur

with open(sys.argv[1], 'w') as f:
    print(init_text, file=f)
    for entry in sub:
        print(f"{entry['start']} --> {entry['end']} {entry['extra_text']}", file=f)
        for s in entry['subs']:
            print(s, file=f)
        print('', file=f)





