#!/bin/env python3

import dbus

try:
    meta = dbus.Interface(dbus.SessionBus().get_object("org.mpris.MediaPlayer2.spotify",
                                                      "/org/mpris/MediaPlayer2"),
                         "org.freedesktop.DBus.Properties").Get("org.mpris.MediaPlayer2.Player", "Metadata")
    print(f"{meta['xesam:title']} : {meta['xesam:artist'][0]} │ ")
except dbus.exceptions.DBusException:
    pass
