#!/bin/python3

import sys

def gtime(st):
    x = st.split(':')
    if len(x) != 3:
        return st
    try:
        h = float(x[0])
    except:
        print(f'Could not turn the hour "{x[0]}" into a float!')
        return st

    try:
        m = float(x[1])
    except:
        print(f'Could not turn the minute "{x[1]}" into a float!')
        return st

    try:
        s = float(x[2].replace(",", "."))
    except:
        print(f'Could not turn the seconds "{x[2]}" into a float!')
        return st

    return 3600 * h + 60 * m + s

def ttime(x):
    ogx = x
    h = x // 3600
    x -= h * 3600
    m = x // 60
    s = x - m * 60
    return f'{int(h):02}:{int(m):02}:{s:.2f}'.replace('.', ',')


def main():
    if len(sys.argv) < 4:
        print("Usage: ./srtCh <inFile> <outFile> <tstamp to offset after> <offset amount>", file=sys.stderr)
        return

    ifname = sys.argv[1]
    ofname = sys.argv[2]
    soff   = gtime(sys.argv[3])
    if soff == sys.argv[3]:
        print(f'"{sys.argv[3]}" is not a valid timestamp', file=sys.stderr)
        return

    try:
        voff = float(sys.argv[4])
    except:
        print(f'Could not transform "{sys.argv[4]}" to a float', file=sys.stderr)
        return

    try:
        iff = open(ifname, "r")
    except:
        print(f'No such file "{ifname}"!', file=sys.stderr)
        return

    lines = iff.readlines()
    iff.close()

    if ofname == '-':
        off = sys.stdout
    else:
        try:
            off = open(ofname, "w")
        except:
            print(f'Cannot create "{ofname}"!', file=sys.stderr)
            return

    start_offset = 0

    for l in lines:
        spl = l.split(' --> ')
        if len(spl) == 1:
            print(l, file=off, end='')
        else:
            t1 = gtime(spl[0])
            t2 = gtime(spl[1])
            if t1 > soff:
                t1 += voff
                t2 += voff
            print(f'{ttime(t1)} --> {ttime(t2)}', file=off)


    off.close()


if __name__ == '__main__':
    main()


