#!/bin/sh

killall wpa_supplicant &> /dev/null
killall dhcpcd &> /dev/null
sleep 0.2
rm /run/wpa_supplicant/wlan*
killall wpa_supplicant &> /dev/null
killall dhcpcd &> /dev/null
sleep 0.2
rm /run/wpa_supplicant/wlan*

ADDR=$(ip a | rg "enp" | head -n 1 | cut -d ':' -f2 | cut -b 2-)

if [ "$1" != "" ]; then
  ADDR=$1
fi

sudo ip a flush dev $ADDR
ip a add 10.10.10.128/24 broadcast 10.10.10.255 dev $ADDR
ip link set up $ADDR
ip route add default via 10.10.10.2 dev $ADDR
ip route add 10.10.0.0/16 via 10.10.10.100 dev $ADDR
ip route add 172.18.0.0/16 via 10.10.10.100 dev $ADDR
ip route add 192.168.1.0/24 via 10.10.10.100 dev $ADDR


echo "nameserver 10.10.10.2" > /etc/resolv.conf
echo "nameserver 1.1.1.1" >> /etc/resolv.conf
