#!/bin/sh
 
HEADLESS_ARG="-display none"
NAME="Linuc"
 
for arg in "$@"; do
  case $arg in
    "gui")
      HEADLESS_ARG=""
      ;;
    *)
      echo "Unkown command $arg"
      ;;
  esac
done
 
echo "Opening $NAME"
 
qemu-system-x86_64 -name $NAME \
                   -drive file=hard_disk.raw,format=raw \
                   -boot menu=on,order=c \
                   -m 10G \
                   -smp cpus=4,cores=2,threads=2,sockets=1 \
                   -enable-kvm \
                   -device virtio-net-pci,netdev=net0,mac=52:54:00:12:34:06 \
                   -netdev type=tap,id=net0,ifname=tap0,script=no,downscript=no \
                   $HEADLESS_ARG
                   # -cdrom debian-live-11.4.0-amd64-standard.iso \

