#!/bin/sh


wget https://resource.dreamtonics.com/download/Synthesizer%20V%20Studio%20Basic/latest/svstudio-basic-linux64-latest.zip
7z x svstudio-basic-linux64-latest.zip
# rm -r /home/raiku/Misc/SynthV
# mv 'Synthesizer V Studio Basic' /home/raiku/Misc/SynthV
# rm svstudio-basic-linux64-latest.zip
