#!/bin/sh

FOLDER="/home/arch/Misc/Utau/.wine/drive_c/Program Files/UTAU/"
EXE="utau.exe"
export WINEPREFIX="/home/arch/Misc/Utau/.wine"
export WINEARCH="win32"
export LANG="ja_JP.UTF-8"
export LC_ALL="ja_JP.UTF-8"
export LC_CTYPE="ja_JP.UTF-8"

cd "$FOLDER"

wine $EXE

