#!/bin/sh    
    
# sudo su    
    
ip tuntap add dev tap0 mode tap user arch    
ip tuntap add dev tap1 mode tap user arch    
brctl addbr br0    
brctl setfd br0 0.0    
brctl addif br0 enp0s31f6    
brctl addif br0 tap0    
brctl addif br0 tap1    
ip link set dev br0 up    
ip link set dev tap0 up    
ip link set dev tap1 up    
ip addr del 192.168.1.111/24 dev enp0s31f6    
ip addr add 192.168.1.111/24 broadcast 192.168.1.255 dev br0    
ip route add default via 192.168.1.100 dev br0    
